---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content/en
  label: Pages
  create: all
- path: content/en/post
  label: Post
  create: all
- path: content/en/documents
  label: Documents
  create: all
- path: content/en/docs
  label: Docs
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.2
